name: Deploy to Server

on:
  push:
    branches:
      - main  # O la rama que estés usando para tus cambios

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.SSH_TARGET }}
            git pull origin main
            docker compose -f docker/production/compose.yml --env-file .env up -d --build
